### ISSUE TITLE
Missing 'soft credit direction' field

### ISSUE THREAD

**Issue by yosefromano** [MegaphoneJon/automaticsoftcredit#3]
after installing the extension, I only see a field to select soft credit type and do not see where to select the soft credit direction.

**Comment by MegaphoneJon** [comment]
Is the custom field present in **Administer » Customize Data and Screens » Custom Fields**?

**Comment by yosefromano** [comment]
Not there either...

**Comment by MegaphoneJon** [comment]
Try uninstalling/reinstalling?  I assume you have the latest version from Github?

**Comment by MegaphoneJon** [comment]
Hmm - I don't see the code in the upgrader.  It may not add the field on upgrade, just on install.  If you can confirm that, I can take action on it.

**Comment by yosefromano** [comment]
will try now

**Comment by yosefromano** [comment]
I see. I installed the extension on civi 5.14.
When I install on civicrm 5.14 I get an error "No such a field" but the extension gets installed and works but the direction field is still not present. 

When I install on civicrm 5.18 it works fine

**Comment by yosefromano** [comment]
Uninstalling doesn't work on 5.14 so I'll have to update to 5.18 and let you know if uninstalling and re-installing creates the field
