### ISSUE TITLE
No soft contribution through online contribution page

### ISSUE THREAD

**Issue by sunnycs121** [MegaphoneJon/automaticsoftcredit#5]
Hi,

Thank you for this beautiful extension but it appears soft contribution is not getting created when contribution is made by user through online contribution page. It is actually adding soft contribution information in `$params` in function "automaticsoftcredit_civicrm_pre" of file "automaticsoftcredit.php" but soft contribution record is not ending up on contact.

Thanks

**Comment by MegaphoneJon** [comment]
Hi Hassan,

I was just able to replicate the issue you're describing on the master branch.  I don't know when this stopped working for online contributions.

Many years ago, I had a version that used the `post` hook that broke when Civi 4.6 was released.  I suspect it would work if I used the `postCommit` hook though.

I don't have an immediate need for this though; is there any chance you're interested in submitting a patch?

**Comment by MegaphoneJon** [comment]
@sunnycs121 I've just released a new version that fixes the issue described.  Note that in rewriting I took advantage of the new table `civicrm_relationship_cache`.  This is tested on Civi 5.31, and will definitely not work on versions before 5.29.

Jon

**Comment by sunnycs121** [comment]
Awesome, also i worked on it just yesterday and used postCommit hook instead of pre which worked for both frontend and backend contributions.
